spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m
  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]
  application:
    name: BE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: studyhub-vectors
        use-tls: false
        initialize-schema: true

app:
  security:
    public-endpoints:
      - "/api/auth/**"
      - "/api/storage/**"
      - "/api/files/**"
      - "/api/user/document/search"
      - "/api/user/academic/**"
  system-admin:
    email: ${SYSTEM_ADMIN_EMAIL}
    password: ${SYSTEM_ADMIN_PASSWORD}
    fullName: ${SYSTEM_ADMIN_FULL_NAME}


jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_SERVICE_KEY}
  storage:
    bucket: Documents
    signed-url-expiration: 3600

springdoc:
  swagger-ui:
    persist-authorization: true