spring:
  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]
  application:
    name: BE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  security:
    public-endpoints:
      - "/api/auth/**"
      - "/api/storage/**"
      - "/api/files/**"

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_SERVICE_KEY}
  storage:
    bucket: Documents
    signed-url-expiration: 3600

springdoc:
  swagger-ui:
    persist-authorization: true