package AiStudyHub.BE.constraint;

public enum ScoreTypeCode {
    UPLOAD_PUBLIC,
    DOC_DOWNLOAD,
    BOOKMARK,
    GOOD_RATING,
    RATING_REPUTATION,
    REPORT_MINOR_FIRST_PENALTY,
    REPORT_MINOR_FINAL_PENALTY,
    ADS_CONTENT_PENALTY,
    DUPLICATE_CONTENT_PENALTY
}
