name: Continuous Integration Pipeline (Maven Build, Package, Docker)
run-name: BE CI triggered by ${{ github.actor }}

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Lý do chạy thủ công'
        required: false
        default: 'Manual test'

concurrency:
  group: be-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/be-ai-study-hub:latest
            ${{ secrets.DOCKER_USERNAME }}/be-ai-study-hub:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max